### ISSUE TITLE
Documentation confusion with certain date filter parameters

### ISSUE THREAD

**Issue by georaldc** [TwilioDevEd/api-snippets#258]
Only noticed this with calls and messages endpoints but the documentation states that date filters can take in equality values for custom date ranges. For example, messages listing

https://www.twilio.com/docs/api/rest/message#list-get

allows ```DateSent<=YYYY-MM-DD``` and ```DateSent>=YYYY-MM-DD``` filters and calls listings

https://www.twilio.com/docs/api/rest/call#list-get

allows ```StartTime<=YYYY-MM-DD``` and ```StartTime>=YYYY-MM-DD```

I'm not sure if this was deprecated or something but I had code that relied on these and I just realized that something was off and the wrong data was being returned now. I then checked some docu examples and the API explorer and it looks like entirely different filters are needed to do ranges (```DateSentAfter```/```DateSentBefore``` for messages and ```StarttimeAfter```/```StarttimeBefore``` for calls)

**Comment by po5i** [comment]
If you are working using the API endpoints (i.e. cURL) you can keep working with `<=` or `>=` but most recent versions of the helper libraries now uses the Before and After suffixes.
