### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'fax'

### ISSUE THREAD

**Issue by sharkwheels** [TwilioDevEd/api-snippets#329]
Hello,

I'm using twilio==6.1.0 and Python 3.5.0. I'm using the code from basic-send.6.x.py and I'm getting an attribute error. Not really sure what's up? Do I have to use a lower version of twilio? Did the syntax change? MMS and SMS are still fine. 

Thanks.

**Comment by jefflinwood** [comment]
Hi, that's an excellent question! 

The Programmable Fax product is accessible through the alpha branch of the current Python SDK. 

Here's the sdk requirement:
twilio==6.1.0-alpha1

Please let me know if that doesn't fix your problem - thanks!

**Comment by sharkwheels** [comment]
Success! Thank you!

**Comment by jefflinwood** [comment]
Glad I could help!
