### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by mengyyy** [TwilioDevEd/api-snippets#406]
[https://github.com/TwilioDevEd/api-snippets/blob/master/rest/messages/send-message/example-1.6.x.py](https://github.com/TwilioDevEd/api-snippets/blob/master/rest/messages/send-message/example-1.6.x.py)
python3 show this 
python2 is OK

**Comment by smendes** [comment]
I've tried with Python 3 and twilio-python 6.3.0 and didn't have any issue. Are you sure you didn't put any `bytes` when using the sample?
