### ISSUE TITLE
PHP Snippets status

### ISSUE THREAD

**Issue by RuslanZavacky** [TwilioDevEd/api-snippets#428]
Hello,

I am curious about the state of the snippets for the PHP lang: is it up to date?

I've tried to follow suggestions from https://www.twilio.com/docs/api/rest/messaging-services, for example:

```php
$service = $twilio->messaging->v1->services->create(
  "My First Service",
  array('statusCallback' => "http://requestb.in/1234abcd")
);
```

And it doesn't seem there is `messaging`, there is `messages`. Also, I wasn't able to find Services there... 

Is this a correct repo to look at - https://github.com/twilio/twilio-php ?

Thank you!

**Comment by imthepitts** [comment]
Hi @RuslanZavacky, 

Sorry for the confusion. You'll need to use the edge version of the helper library to access beta features:

> Public Beta
> Twilio's Messaging Services API is currently available as a Public Beta product. Some features are not yet implemented and others may be changed before the product is declared as Generally Available.
> 
> Public Beta products are not covered by a Twilio SLA.
> Code samples are written using the "Edge" (aka "alpha" branch) versions of the Twilio helper libraries. 
> 

You can access the edge branch here:
https://github.com/twilio/twilio-php/tree/alpha

If you need further assistance, please reach out to our support team:
https://www.twilio.com/console/support/tickets/create 

All the Best,

Zack

**Comment by RuslanZavacky** [comment]
Indeed, thank you @imthepitts :) Somehow I've missed yellow part... jumped straight to the examples )
