### ISSUE TITLE
Cannot load a single member from channel

### ISSUE THREAD

**Issue by anhang** [TwilioDevEd/api-snippets#438]
Following the directions here to retrieve a member: https://www.twilio.com/docs/api/chat/rest/members?code-sample=code-retrieve-a-member&code-language=rb&code-sdk-version=5.x

> 2.4.0 :125 > channel.members("my-name")
> ArgumentError: wrong number of arguments (given 1, expected 0)
> 	from /home/az/.rvm/gems/ruby-2.4.0/gems/twilio-ruby-5.0.0.rc21/lib/twilio-ruby/rest/chat/v2/service/channel.rb:484:in `members'

(I'm using twilio-ruby 5.0.0.rc21)

**Comment by hortega** [comment]
Try with twilio-ruby 5.0.0, it was released last week:
https://rubygems.org/gems/twilio-ruby/versions/5.0.0
