### ISSUE TITLE
all python snippets for Copilot, SDK version 6.x error

### ISSUE THREAD

**Issue by biskit** [TwilioDevEd/api-snippets#447]
env: python 2.7.5, twilio==6.4.3

pls run any sample from this page
https://www.twilio.com/docs/api/rest/messaging-services and selecting python as the language.

for eg: 
https://github.com/TwilioDevEd/api-snippets/blob/master/messaging/services/service-create/service-create.6.x.py 
and every sample will error like this:

`
AttributeError: 'Client' object has no attribute 'messaging'
`

**Comment by po5i** [comment]
Tested now with Python 2.7.10 and twilio==6.12.0 and I got it working. Maybe you can try reinstalling the libraries using `pip`.
