### ISSUE TITLE
python SDK twilio.rest

### ISSUE THREAD

**Issue by biskit** [TwilioDevEd/api-snippets#449]
the 'messaging' object is available in 6.4.2-alpha1 https://twilio.github.io/twilio-python/6.4.2-alpha-1/rest/index.html , but not in 6.4.3 https://twilio.github.io/twilio-python/6.4.3/rest/index.html or 6.4.3a1 https://twilio.github.io/twilio-python/6.4.3a1/rest/index.html.

however, all documentation for https://www.twilio.com/docs/api/rest/sending-messages-copilot for python says 6.x and not mentioning the above caveat.

is 'messaging' gonna be supported?

**Comment by joliveros** [comment]
@biskit , it looks like you may be trying to use a feature that is in preview. In which case you should use the  version of the api you want and append `-alpha1`

For instance, if you want to use the alpha version of `6.4.3` you should install `6.4.3-alpha1`

**Comment by biskit** [comment]
I was pointed to that on StackOverflow https://stackoverflow.com/questions/45287170/samples-code-for-twilio-copilot-sdk-6-x-for-python-have-errors by a kind observer.

It would have all been nicer if the page https://www.twilio.com/docs/api/rest/sending-messages-copilot only said that instead of saying "Public Beta" and had some python specific comments on it.

**Comment by po5i** [comment]
Now `messaging` is supported since `6.6.0`

**Comment by biskit** [comment]
👍
