### ISSUE TITLE
Twilio.com documentation is out of sync with Github documentation

### ISSUE THREAD

**Issue by samdec** [TwilioDevEd/api-snippets#569]
Apologies if this is the wrong place, but the docs on twilio.com link to this repo and the two appear to be out of sync, at least in this particular example. 
![](https://monosnap.com/file/7lQRPVHHs5ugM5LX9K9fi6fcAtS1Uf.png)

**Comment by po5i** [comment]
Thanks for sharing, and sorry for the late response. They could be out of sync at that time.
