### ISSUE TITLE
create() got an unexpected keyword argument 'ttl'

### ISSUE THREAD

**Issue by Brodan** [TwilioDevEd/api-snippets#573]
I was copy/pasting some Python code from the [Sync docs](https://www.twilio.com/docs/api/sync/rest/lists#create-a-list) and it seems that the code in [this](https://github.com/TwilioDevEd/api-snippets/blob/master/sync/rest/lists/create-list/create-list.6.x.py) snippet is erroneous.

When running the following:
```
list_instance = client.sync \
    .services("XXXXXXXXXXXXXXXXXXXXXXXX") \
    .sync_lists \
    .create(unique_name="ExampleList", ttl=1814400)
```
I get this output:
```
(venv) chranj@~/Documents/twilio-sync-tests$ python create_list.py 
Traceback (most recent call last):
  File "create_list.py", line 13, in <module>
    .create(unique_name="QuestList", ttl=1814400)
TypeError: create() got an unexpected keyword argument 'ttl'
```

**Comment by dprothero** [comment]
Brodan, it's a new paramater. Update your Twilio python library to the latest version, or omit the ttl variable.

**Comment by Brodan** [comment]
@dprothero Thank you! I was on `6.8.1`, didn't think it was _that_ new of a parameter!

**Comment by dprothero** [comment]
Shipped yesterday :)
