### ISSUE TITLE
TypeError: tc.messagingClient.getSubscribedChannels is not a function

### ISSUE THREAD

**Issue by riyajk** [TwilioDevEd/api-snippets#594]
Hello Team,

I have created Twilio chat client.

**tc.messagingClient = new Twilio.Chat.Client(token);**

Now,I am accessing the `getSubscribedChannels ` function.

```
tc
      .messagingClient
      .getSubscribedChannels()
      .then((paginator)=> {

        console.log(paginator);
        for (i = 0; i < paginator.items.length; i++) {
          var channel = paginator.items[i];
          console.log('Channel: ' + channel.friendlyName);
        }
      },(error)=>console.log(error));
```

But I am getting the error 
**TypeError: tc.messagingClient.getSubscribedChannels is not a function**

I am using below js files related for Twilio.

```
script(src="//media.twiliocdn.com/sdk/js/common/releases/0.1.5/twilio-common.js")
script(src="//media.twiliocdn.com/sdk/js/chat/releases/0.11.1/twilio-chat.js")
```
I have checked the inherited function in Twilio chat client object,but the `getSubscribedChannels` function is not listed there event.
![twilio](https://user-images.githubusercontent.com/12458279/35316524-204e1274-00f8-11e8-98ec-98ff561f2d24.png)

**Comment by po5i** [comment]
Hi, sorry for the late response.

It looks like you have to use `getPublicChannels()` method like [this tutorial](https://github.com/TwilioDevEd/twiliochat-node/blob/master/public/js/twiliochat.js#L130).
