### ISSUE TITLE
Proxy Example Wrong

### ISSUE THREAD

**Issue by dikirill** [TwilioDevEd/api-snippets#607]
Fix (https://github.com/TwilioDevEd/api-snippets/pull/605) you applied to #604 doesn't actually right.
According to latest changes to the library (5.16.4):
https://github.com/twilio/twilio-hp/blob/master/Twilio/Rest/Proxy/V1/Service/Session/ParticipantList.php#L136
Your change should look more like:

```
$client = new Client($sid, $token);
$session = $client
    ->proxy
    ->services("KSXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    ->sessions("KCXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
    ->participants->create("+15558675310",
        array(
            "friendlyName" => "Alice"
        )
    );
```

**Comment by joliveros** [comment]
Thanks for catching that @dikirill. I can confirm after looking at the integration tests: 
https://github.com/twilio/twilio-php/blob/master/Twilio/Tests/Integration/Proxy/V1/Service/Session/ParticipantTest.php#L114

**Comment by joliveros** [comment]
this should be fixed in the following commit: https://github.com/TwilioDevEd/api-snippets/commit/5725946a0a288610e74aa02f38e7138f9c891cf2
