### ISSUE TITLE
TaskQueue Capability Token Generation for node.js is just the Worker capability token generation

### ISSUE THREAD

**Issue by ggaabe** [TwilioDevEd/api-snippets#618]
It seems like the code for generating a worker capability token was simply copy and pasted to the taskqueue one. In the meantime, there's no docs on generating a taskqueue capability token on node.

https://github.com/TwilioDevEd/api-snippets/blob/master/rest/taskrouter/jwts/taskqueue/example-1/example-1.3.x.js

**Comment by po5i** [comment]
Hi! the file you mention has been updated.
