### ISSUE TITLE
Missing ducumentation for conference.update for nodejs

### ISSUE THREAD

**Issue by oliverhr** [TwilioDevEd/api-snippets#631]
https://www.twilio.com/docs/voice/api/conference#end-a-conference-by-id

just shows how to update via CURL but in Twilio-Node exists an update method: 

https://github.com/twilio/twilio-node/blob/b5f475e5727f74dcd741ec47754f1aed2be7e96e/lib/rest/api/v2010/account/conference.js#L487

https://github.com/twilio/twilio-node/blob/b5f475e5727f74dcd741ec47754f1aed2be7e96e/lib/rest/api/v2010/account/conference.js#L609

**Comment by po5i** [comment]
Hi, thanks for let us know. This code can help you while we update the documentation:
```js
// Download the helper library from https://www.twilio.com/docs/node/install
// Your Account Sid and Auth Token from twilio.com/console
const accountSid = 'ACaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
const authToken = 'your_auth_token';
const client = require('twilio')(accountSid, authToken);

client.conferences('CFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa')
      .update({status: 'completed'})
      .then(conference => console.log(conference.sid))
      .done();
```

**Comment by oliverhr** [comment]
thanks @po5i – Carlos – I have another questions related to this issue, i hope you can answer here.

1.  In the code at the top of each module we can read this legend "This code was generated by" and an ASCII art I can read Yoyodine. Is that a Joke? or you guys at twilio are transpiling from a different source code?

2. About conferences, What are the difference between this two classes: ConferenceInstance, ConferenceContext?

**Comment by po5i** [comment]
Indeed, Yoyodyne is one of our internal tools.

I'm not sure how to answer (2) since it's not related to me, afaik they're internal classes so the client can return them when necessary.
