### ISSUE TITLE
deleting time range recordings 

### ISSUE THREAD

**Issue by eman-moh** [TwilioDevEd/api-snippets#634]
I need to delete call recordings of time range using twilio node SDK 3.X here is the code I used: 
```
client.recordings
   .each({
      dateCreatedBefore:  '2017-12-30',
      dateCreatedAfter: '2017-11-01',
  }, (recording)=>{
client.recordings(recording.sid).remove();
});
```
 I need a way to know when all the recordings are deleted successfully or some failed .. how can I use Promise.all with ```client.recordings.each```

**Comment by po5i** [comment]
As you can in [this code snippet](https://github.com/TwilioDevEd/api-snippets/blob/master/rest/recording/instance-delete-examples/instance-delete-examples.3.x.js):

```js
client
  .recordings(recordingSid)
  .remove()
  .then(() => console.log(`Sid ${recordingSid} deleted successfully.`))
  .catch(err => {
    console.log(err.status);
    throw err;
  });
```

The `remove()` function returns a Promise. You may push its return value to a list of Promises and then process them as you want.

Also the `remove()` function can take a callback argument which is a function to handle processed record.
