### ISSUE TITLE
docs/fax/receive - snippet with res.body.MediaUrl should be req.body.MediaUrl

### ISSUE THREAD

**Issue by PatNeedham** [TwilioDevEd/api-snippets#660]
On [https://www.twilio.com/docs/fax/receive](https://www.twilio.com/docs/fax/receive), right hand side Node.js example contains this:
```
// Define a handler for when the fax is finished sending to us - if successful,
// We will have a URL to the contents of the fax at this point
app.post('/fax/received', (req, res) => {
  // log the URL of the PDF received in the fax
  console.log(res.body.MediaUrl);

  // Respond with empty 200/OK to Twilio
  res.status(200);
  res.send();
});
```

That matches up with [line 29 in `basic-receive.js`](https://github.com/TwilioDevEd/api-snippets/blob/master/fax/basic-receive/basic-receive.js#L29).

Sending a fax to a number on our Twilio account (that has the webhook connected to a running Express server with this code) results in `TypeError: Cannot read property 'MediaUrl' of undefined` on that line. While `req.body` contains keys `FaxSid, ApiVersion, MediaUrl, NumPages, FaxStatus, To, From, AccountSid, RemoteStationId`

**Comment by po5i** [comment]
Good catch! Thank you.
