### ISSUE TITLE
Improper use of const in C# Sms Sample

### ISSUE THREAD

**Issue by captain-keystone** [TwilioDevEd/api-snippets#669]
Source: https://github.com/TwilioDevEd/api-snippets/blob/4715c8eb78743eb7230190043ac9922f312782b4/rest/messages/generate-twiml-dynamic-sms/generate-twiml-dynamic-sms.5.x.cs
Documentation: https://www.twilio.com/docs/sms/tutorials/how-to-receive-and-reply-csharp

Line 13:
`const string requestBody = Request.Form["Body"];`

It appears that the const keyword is being used here as if in javascript rather than C#.

`Request.Form["Body"]` is not a compile time constant in any scenario I can imagine, and a compiler error will be thrown. 

It should be changed to `string requestBody...` or simply to `var requestBody`

**Comment by dprothero** [comment]
Thanks for the bug report! I just fixed it.
