### ISSUE TITLE
Gather Digits no where to be found in request body

### ISSUE THREAD

**Issue by RadAcademy** [TwilioDevEd/api-snippets#671]
Examples of the code to retrieve digits entered by clients into the phone is no where to be found.

"request.body.Digits" is meant to be the location but the code is broken and Digits never are found by the code.

For example: https://github.com/TwilioDevEd/api-snippets/blob/master/guides/voice/gather-dtmf-tones-guide/gather-example-step-2/example.3.x.js

**Comment by seannybgoode** [comment]
Yeah. This sample code doesn't even compile for me. I'm curious what versions of the library are being used.

**Comment by RadAcademy** [comment]
Seanny I'll get back to you this evening with working code if you need it. I had to add some properties I had missed, it wasn't sending any data.

**Comment by po5i** [comment]
This code sample is part of this tutorial: [Gather User Input via Keypad (DTMF Tones) in Node.js](https://www.twilio.com/docs/voice/tutorials/how-to-gather-user-input-via-keypad-node-js) 

There is more code in the previous steps to consider
