### ISSUE TITLE
composer.json in root of project

### ISSUE THREAD

**Issue by kwhinnery** [TwilioDevEd/api-snippets#82]
Why is this located here? it would seem to be a concern of the test harness used to execute the snippets, and not something globally required for the project.

**Comment by mcelicalderon** [comment]
Makes sense. I will move anything related to the test harness inside the `tools/snippet_testing` directory

**Comment by mcelicalderon** [comment]
Actually, just removing this from the repo. Nuget and composer dependencies will still be installed at root dir if you are running the tests only.

**Comment by mcelicalderon** [comment]
Fixed in a004d3b813ae0fdf2b24fc8a6a7f812f171175a2
