### ISSUE TITLE
How to use spanish word in say verb

### ISSUE THREAD

**Issue by vinu1421** [TwilioDevEd/api-snippets#925]
I'm facing the below issue

response.say('Un párrafo es una serie de oraciones relacionadas que desarrollan una idea central, llamada tema. Trate de pensar en los párrafos en términos de unii
dad temática.', language='es-ES')

Output:

`<?xml version="1.0" encoding="UTF-8"?><Response><Say language="es-ES">Un p&#225;rrafo es una serie de oraciones relacionadas que desarrollan una idea central, llamada tema. Trate de pensar en los p&#225;rrafos en t&#233;rminos de unidad tem&#225;tica.</Say><Pause length="3" /></Response>`

The above is casuing Document parse failure

**Comment by bld010** [comment]
Hi @vinu1421 , can you try the following: 

```
twiml.say({language: 'es-ES'},`Un párrafo es una serie de oraciones relacionadas que desarrollan una idea central, llamada tema. Trate de pensar en los párrafos en términos de unii
dad temática.`);
```

**Comment by bld010** [comment]
Hi @vinu1421,
Which helper library are you using?
